aos:
 aos_host: https://vpc-llm-imdb-search-wdv7w5ydpuuzhekveyxmnhsnw4.us-east-1.es.amazonaws.com
 aos_user: root
 aos_pass: MyOpenSearch01@
 aos_index: imdb_small_posters
 aos_knn_index: imdb_plot_knn

llm:
  ai21_instruct: j2-jumbo-instruct

TMDB_API_TOKEN: TMDB_API_TOKEN

