corpus:
  path14A_html: ../data/14A/
  path14A_frag: ../data/14A_frags/
  path14A_meta: ../data/14A_meta/
  
kendra:
  index_id: fbaf5fc4-306f-4e06-886c-99437516bfbb
  region_name: us-east-1
  data_source: s3://kendra-index-1/documents/
  
aos:
 aos_host: search-my-domain-03-wjasay6aycgw2xrzp4fh3c7xru.us-east-1.es.amazonaws.com
 aos_user: root
 aos_pass: MyOpenSearch01@
 aos_index: my-index-05

llm:
  t5_endpoint: jumpstart-example-huggingface-text2text-2023-06-09-17-38-20-848
  ai21_instruct: j2-jumbo-instruct-personalization

HUGGINGFACEHUB_API_TOKEN: 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

